name: Deploy API Server

on:
  push:
    branches:
      - main
    paths:
      - 'prisma/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest
          secrets: |
            "NODE_ENV=${{ secrets.NOD_ENV }}"
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "JWT_SECRET=${{ secrets.JWT_SECRET }}"
            "TZ=${{ secrets.TZ }}"

      - name: Deploy Docker to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          allenvs: true
          script: |
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d
